### ISSUE TITLE
Maintenance help needed?

### ISSUE THREAD

**Issue by alloy** [danielmoore/ts-babel-node#13]
At Artsy we’re using this tool on a daily basis and I noticed that [this PR](https://github.com/danielmoore/ts-babel-node/pull/10) by a co-worker had been sitting a while. If you have limited time at the moment, we (@orta and I) would be available to help out with maintenance and releasing.

**Comment by danielmoore** [comment]
Thanks for the offer! You're both collaborators now

**Comment by alloy** [comment]
Thanks!

**Comment by orta** [comment]
Amazing - thanks @danielmoore 

Any chance you can add one of us to the NPM module too, https://www.npmjs.com/~orta https://www.npmjs.com/~alloy ( https://www.npmjs.com/package/ts-babel-node/access )

**Comment by alloy** [comment]
Watch out, my current npm handle is alloy020!

**Comment by alloy** [comment]
(The ‘alloy’ handle is squatted)
