### ISSUE TITLE
Support for .tsx files

### ISSUE THREAD

**Issue by LKay** [danielmoore/ts-babel-node#8]
Seems like any configuration around processing JSX-like files fails and compiling to pure javascript fails. The files with `*.tsx` extensions are ignored and jsx code is left unchanged even though `.babelrc` contains proper configuration. 

The error looks like:

```
/Projects/some_app/test/components/forms/field-text.specs.tsx:17
                const wrapper = enzyme_1.shallow(<FieldText_1.FieldText {...props}/>);
                                                 ^
SyntaxError: Unexpected token <

```

My `mocha.opts` is:

```
--require jsdom-global/register
--require babel-polyfill
--require ts-babel-node/register
--require ./test/utils/index.ts

```

`tsconfig.json`:

```
{
    "compilerOptions": {
        "jsx": "preserve",
        "module": "commonjs",
        "removeComments": true,
        "sourceMap": true,
        "target": "es6",
        "moduleResolution": "node"
    }
}
```

`.babelrc`:

```
{
  "presets": [
    ["es2015", { "modules" : false, "loose" : true }], "react"
  ]
}

```

Any way to run JSX tests in typescript using `ts-babel-node`?

**Comment by danielmoore** [comment]
Yep, `.tsx` files aren't supported yet. This is also a good reason to implement #5, since your `.babelrc` is different from the one built in.
